name: Release

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Minify javascript file
        
      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          body_path: CHANGELOG.txt
          files: services-component.min.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
